import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { HerouiProvider } from "@/components/providers/nextTheme";
import DebugOutline from "@/components/common/debugging-outline";
import AuthProvider from "@/components/providers/authentication";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Clerk Next.js Quickstart",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased bg-background text-foreground`}
            suppressHydrationWarning
            data-reduce-motion="false"
        >
            <body className="min-h-full h-dvh w-full">
                <HerouiProvider>
                    <ClerkProvider>
                        <AuthProvider>
                            {/* <Header/> */}
                            {children}
                        </AuthProvider>
                    </ClerkProvider>
                </HerouiProvider>
                <DebugOutline />
            </body>
        </html>
    );
}
